# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 075040d227320af32ba057671fea23698139abd54af80fcf846afc9ab33bc1233cdbf934a7e56e9f3d01f20280efa47f179837f7ee1e7d1691926b6bd80ccccc

test:
  secret_key_base: a6b7a31738dc0b9f8565ca1dd503e102243c41750da5099e69001354c10ceb0800d8a8108712c3305d4c56c75123d6d89a9e14eec79ff8a9f5f520df90f0deb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
